### ISSUE TITLE
[suggestion] Symfony Bundle option?

### ISSUE THREAD

**Issue by AndrewCarterUK** [php-pm/php-pm-httpkernel#29]
Hello,

Thank you for your work on this - it was a great inspiration for a project of mine ([PHPFastCGI](http://github.com/PHPFastCGI)) that I've had much enjoyment and success with.

My suggestion is for you to provide a bundle integration for your project to the Symfony framework. You can use the container to retrieve the kernel as a service (for handling requests) and you can insert console commands directly into the application.

I can see that this set up allows you to bootstrap Symfony and Laravel - and my suggestion would only work for Symfony, but the ease of installation makes it a very appealing option. Getting going is as simple as composer requiring a bundle, adding it to the kernel, and away you go - a process Symfony users are very familiar with.

I've already done this with PHPFastCGI: [Speedfony Bundle](https://github.com/PHPFastCGI/SpeedfonyBundle) so this may be a useful reference for you.

Anyway, keep up the good work - and I won't be offended if you close this for not being a route that you want to go down :)

**Comment by marcj** [comment]
Hey @AndrewCarterUK, thank you very much for your feedback! highly appreciated :)

We went the other path, by initialize the kernel ourselves, so had full access to the kernel. The good part about this is, that the user does not need to modify its application in any way (at least in theory :smile: memory leaks will results in a modification).

Did you get any limitation with your PHPFastCGI? I ask because I guess we do currently the same work (reading cookies, headers, request body and pass it into a SymfonyRequest, and then vice-versa SymfonyResponse to http output). I'm not sure whether we can eliminate some work by just merging our project together, if possible, so that PPM spawns little fastcgi server, that do the same, so we don't need to fully implement http/1.1,2 specs.

**Comment by AndrewCarterUK** [comment]
The main limitation I've had is handling uploaded files. I'm not sure if it's a limitation as much as something that I just haven't got around to!

I'm also doing a lot of working on trying to create an interoperable application event loop that would allow for better support of async programming techniques (returning a response promise for example). I'm currently working on a standard for this alongside React PHP, Icicle and AMP that could eventually become a FIG PSR ([check here](https://github.com/async-interop/event-loop/pull/3/files)).

I'm also very happy to look into the possibility of sharing some of the work load between our projects. My current focus is on async support as I think this will change quite significantly how our projects are structured (if you decide this is something you'd like to support too).

**Comment by andig** [comment]
Uploaded file handling should meanwhile be working as well- closing.
